title: some random rants
email: tchaikov@gmail.com
description: 我的学习记录
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.k3fu.xyz"
github_username:  tchaikov

lang: "en"

author:
  name: Kefu Chai
  url: "https://blog.k3fu.xyz"
  bio: yet another lamer
  email: tchaikov@gmail.com
  github: tchaikov

repository: tchaikov/random-rants
repository_tree: master

paginate: 8
paginate_path: /page:num

exclude:
  - Gemfile.lock
  - Gemfile
  - Makefile
  - README.adoc
  - LICENSE
  - /vendor
  - /docs
  - /assets/node_modules

header_text: 一亩三分地
excerpt: true
post_navigation: true
katex: true

paginate: 5
paginate_path: "/blog/page:num"

keep_files:
  - images
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - stem
    - icons=font
    - imagesdir=/images
    - source-highlighter=rouge

sass:
    sass_dir: _sass
    style: nested

theme: type-on-strap

