= Ceph 中的 Paxos
:page-tags: [ceph, distributed-system]
:date: 2020-10-11 12:21:43 +0800
:pp: {plus}{plus}
:toc: left
:!toc-title:

每个项目都会实现自己的 Paxos，在工程上根据各自情况有自己的权衡。Ceph 也是这样。

toc::[]

这篇文章希望讨论一下 Ceph 里面对最初的 Paxos 做了哪些改变，修改的原因又是什么。

== Paxos

https://lamport.azurewebsites.net/pubs/paxos-simple.pdf[Paxos Made Simple] 可能是最好的一篇说
Paxos 的论文。这里不准备简单地复述它。而是想把 Paxos 放在一个特定的上下文去解释它。

就像 TCP 一样，Paxos 可以说是某一类协议。这类协议有一些特定的特征，解决一个特定的问题，也有各自不同的地方。
为了便于后面说明，我们虚拟一个场景。老王、老李和老张商量着周六聚一下，一起吃个饭，但是他们对于在哪儿吃，
吃什么还没有达成一致。可以说，这三个人就组成了一个分布式系统。他们需要做出一些决定，让大家都能达成一致。
就算有人临时不在手机旁边，或者没接到电话，也能让饭局成行。

这里提一下 Paxos 中的几种角色。

Acceptor::
能投票的人，他们做出决定。在这个故事里，他们就是老王、老李和老张。这几个人为了组织这场饭局，搞了个微信群，
群的名字就叫"DCS"。
Proposer::
提出提议的一方，它负责劝说 Acceptor 接受提议。如果有冲突的话，它还负责协调，解决冲突，让提议能往前推进。
很明显，这几位都是 proposer。当然，proposer 可以帮一些局外人带话，比如老张的媳妇，她很关心老张，建议大家
还是吃点清淡的。要不去楼下的兰州粥店？于是这个建议没有在老张这里停留，立即传达到了 DCS 群。
Learner:: 
接受提议的人。所有做出的决定都会发往这些人。这里可能还有其他人，比如说饭局的常规组织者老赵，他对订餐流程和
各种打折规则烂熟于胸，更熟悉周末的交通状况，虽然在异国出差，他仍然牵挂着大家，为大家提供各种咨询服务。
所以这次饭局中，learner 是老王、老李、老张和资深搓饭顾问老赵。

所以在这个系统里面，老王、老李和老张身兼三职：acceptor、proposer 和 learner。老赵是场外指导，只担任 learner。
因为大家通过手机联系，而手机有时候不在身边，有时候因为开会或者工作不方便查看，所以消息无法保证及时回应或者
被看到。

而大家需要先确定这么三个要素

. 具体的时间。是五点半，还是六点，或者干脆晚一点儿，七点。
. 大概的方位。是五角场，还是徐家汇，或者在静安寺找个地方。
. 在哪家店。是过桥米线，兰州拉面，沙县小吃，还是重庆鸡公煲？

他们这么讨论，

. 

在几位讨论的时候，。老张不敢怠慢，马上把消息转到了
DCS 群。不过老是让老张传话，太不方便了，于是把老张的 proposer 权限被取消了，自己成为了 proposer。
而老张被取消了 proposer 资格，只留下了 acceptor 的角色。


