title: some random rants
email: tchaikov@gmail.com
description: >-
  我的学习记录
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.k3fu.xyz"
github_username:  tchaikov

markdown: kramdown
kramdown:
  math_engine: sskatex
  math_engine_opts:
    katex_js: 'js/katex.min.js'
    katex_opts:
      output: 'mathml'
      throwOnError: true
# Build settings
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
